- name: SElinux disabled
  lineinfile: dest=/etc/sysconfig/selinux
              regexp="{{ item.regexp }}"
              line="{{ item.line }}"
  with_items:
   - { regexp: 'SELINUX=', line: 'SELINUX=disabled' }

- name: change SELINUX disable
  selinux: state=disabled
