- hosts: servers
  sudo: yes
  roles:
    - { role: hosts, tags: hosts }
    - { role: ssh, tags: ssh }
    - { role: bash, tags: bash }
    - { role: selinux, tags: selinux }
    - { role: nagios_client, tags: nagios_client }
  handlers:
    - include: handlers/main.yml

- hosts: send-servers
  sudo: yes
  roles:
    - { role: mail, tags: mail }

- hosts: nfs-servers
  sudo: yes
  roles:
    - { role: nfs_client, tags: nfs_client }
