---
- name: be sure basic package is installed
  yum: name="{{ item }}" state=present
  with_items:
   - epel-release
   - nagios-nrpe
   - nagios-plugins-all

- name: configure nrpe
  copy: src=nrpe.cfg.j2 dest=/etc/nagios/nrpe.cfg owner=root group=root mode=0644
  notify:
   - restart_nrpe

- name: check if firewalld is running
  command: systemctl is-active firewalld
  register: firewalld_result
  changed_when: False
  ignore_errors: True  # rc is 3 when firewalld is stopped

- name: set the port state 5666/udp
  firewalld: port=5666/udp state=enabled immediate=yes permanent=true
  notify: reload_firewalld
  when: firewalld_result.stdout == "active"

- name: set the port state 5666/tcp
  firewalld: port=5666/tcp state=enabled immediate=yes permanent=true
  notify: reload_firewalld
  when: firewalld_result.stdout == "active"

#- name: change /etc/nagios/nrpe.cfg
#  lineinfile: dest=/etc/nagios/nrpe.cfg
#              regexp="{{ item.regexp }}"
#              line="{{ item.line }}"
#  with_items:
#    - { regexp: '^command[check_smtp]', line: 'command[check_smtp]=/usr/lib64/nagios/plugins/check_smtp -w $ARG1$ -c $ARG2$' }
#    - { regexp: '^command[check_mem]', line: 'command[check_mem]=/usr/lib64/nagios/plugins/check_mem -w $ARG1$ -c $ARG2$' }
#    - { regexp: '^command[check_swap]', line: 'command[check_swap]=/usr/lib64/nagios/plugins/check_swap -w $ARG1$ -c $ARG2$' }
