- name: restart_journald
  service: name=systemd-journald state=restarted

- name: journald_is_running
  service: name=systemd-journald state=started

- name: restart_rsyslog
  service: name=rsyslog state=restarted
