- name: configure hosts
  template: src=hosts dest=/etc/hosts owner=root group=root mode=0644

#- name: change /etc/hosts
#  replace: dest=/etc/hosts
#              regexp="{{ item.regexp }}"
#              replace="{{ item.replace }}"
#  with_items:
#   - { regexp: '192.168.0.100 windows\n', replace: '' }
